# Generated by Django 5.2.11 on 2026-02-25 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.BigAutoField(db_column='community_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'community',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.BigAutoField(db_column='conversation_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_group', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.BigAutoField(db_column='page_id', primary_key=True, serialize=False)),
                ('page_name', models.CharField(max_length=255)),
                ('page_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(db_column='comment_id', primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_user', models.ForeignKey(blank=True, db_column='author_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_as_user', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
                ('author_page', models.ForeignKey(blank=True, db_column='author_page_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_as_page', to='api.page')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('academic_email', models.EmailField(db_column='academic_email', max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_verification',
                'indexes': [models.Index(fields=['academic_email'], name='email_verif_academi_1a8b83_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(db_column='message_id', primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
                ('sender_user', models.ForeignKey(blank=True, db_column='sender_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('sender_page', models.ForeignKey(blank=True, db_column='sender_page_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='api.page')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(db_column='notification_id', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('events', 'Events'), ('comments', 'Comments'), ('accepted_friend_request', 'Accepted friend request'), ('messages', 'Messages'), ('announcements', 'Announcements')], max_length=30)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='instructor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('academic_title', models.CharField(blank=True, choices=[('dr', 'Doctor'), ('prof', 'Professor'), ('asst', 'Assistant'), ('lecturer', 'Lecturer'), ('adviser', 'Adviser')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('instructor_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=10)),
                ('university_page', models.ForeignKey(blank=True, db_column='university_page_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='api.page')),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='FollowPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='page_follows', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='api.page')),
            ],
            options={
                'db_table': 'follow_page',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(db_column='event_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('page', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.page')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=50)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.conversation')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_column='page_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='api.page')),
            ],
            options={
                'db_table': 'conversation_member',
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('comment_reaction_id', models.BigAutoField(db_column='comment_reaction_id', primary_key=True, serialize=False)),
                ('comment', models.ForeignKey(db_column='comment_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.comment')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_column='page_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to='api.page')),
            ],
            options={
                'db_table': 'comment_reaction',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(db_column='post_id', primary_key=True, serialize=False)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('announcement', 'Announcement'), ('advertisement', 'Advertisement'), ('academy', 'Academy'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_page', models.ForeignKey(blank=True, db_column='author_page_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_as_page', to='api.page')),
                ('author_user', models.ForeignKey(blank=True, db_column='author_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_as_user', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, db_column='community_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api.community')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post'),
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('media_id', models.BigAutoField(db_column='media_id', primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('url', 'URL')], max_length=10)),
                ('media_url', models.URLField()),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.post')),
            ],
            options={
                'db_table': 'post_media',
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('post_reaction_id', models.BigAutoField(db_column='post_reaction_id', primary_key=True, serialize=False)),
                ('page', models.ForeignKey(blank=True, db_column='page_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reactions', to='api.page')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.post')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_reaction',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(db_column='report_id', primary_key=True, serialize=False)),
                ('reported_content_id', models.BigIntegerField(db_column='reported_content_id')),
                ('content_type', models.CharField(choices=[('harassment_abuse', 'Harassment & Abuse'), ('violence_harm', 'Violence & Harm'), ('sexual_content_exploitation', 'Sexual Content & Exploitation'), ('child_safety', 'Child Safety'), ('hate_extremism', 'Hate & Extremism'), ('self_harm_dangerous_behavior', 'Self-Harm & Dangerous Behavior'), ('misinformation_manipulation', 'Misinformation & Manipulation'), ('privacy_impersonation', 'Privacy & Impersonation'), ('spam_scams_fraud', 'Spam, Scams & Fraud'), ('illegal_ip_violations', 'Illegal & Intellectual Property Violations')], max_length=50)),
                ('reason', models.TextField()),
                ('final_action', models.CharField(choices=[('content_removal', 'Content removal'), ('warning_strike', 'Warning / Strike'), ('temp_restriction', 'Temporary restriction (limited features or short suspension)'), ('temp_suspension', 'Temporary suspension'), ('permanent_ban', 'Permanent ban'), ('account_deletion', 'Account deletion'), ('content_labeling', 'Content labeling (warning / sensitive tag)'), ('report_authorities', 'Report to authorities (for severe illegal cases)')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter_page', models.ForeignKey(blank=True, db_column='reporter_page_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_as_page', to='api.page')),
                ('reporter_user', models.ForeignKey(blank=True, db_column='reporter_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_as_user', to=settings.AUTH_USER_MODEL)),
                ('university_page', models.ForeignKey(blank=True, db_column='university_page_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to='api.page')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('academic_level', models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=20)),
                ('university_page', models.ForeignKey(blank=True, db_column='university_page_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.page')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('academic_email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline'), ('suspended', 'Suspended')], default='online', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(db_column='community_id', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.community')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_member',
                'constraints': [models.UniqueConstraint(fields=('community', 'user'), name='uniq_community_user')],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('reminder_id', models.BigAutoField(db_column='reminder_id', primary_key=True, serialize=False)),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.event')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_reminder',
                'constraints': [models.UniqueConstraint(fields=('event', 'user', 'reminder_time'), name='uniq_event_user_time')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('friendship_id', models.BigAutoField(db_column='friendship_id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('user1', models.ForeignKey(db_column='user1_id', on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(db_column='user2_id', on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friendship',
                'constraints': [models.UniqueConstraint(fields=('user1', 'user2'), name='uniq_friendship_pair')],
            },
        ),
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('media_id', models.BigAutoField(db_column='media_id', primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('url', 'URL')], max_length=10)),
                ('media_url', models.URLField()),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.message')),
            ],
            options={
                'db_table': 'message_media',
                'constraints': [models.UniqueConstraint(fields=('message', 'order_index'), name='uniq_message_media_order')],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('message_reaction_id', models.BigAutoField(db_column='message_reaction_id', primary_key=True, serialize=False)),
                ('message_reaction_type', models.CharField(max_length=50)),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.message')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_column='page_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='api.page')),
            ],
            options={
                'db_table': 'message_reaction',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('page__isnull', True)), models.Q(('user__isnull', True), ('page__isnull', False)), _connector='OR'), name='chk_message_reaction_author'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('message', 'user', 'message_reaction_type'), name='uniq_msg_reaction_user_type'), models.UniqueConstraint(condition=models.Q(('page__isnull', False)), fields=('message', 'page', 'message_reaction_type'), name='uniq_msg_reaction_page_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sender_user__isnull', False), ('sender_page__isnull', True)), models.Q(('sender_user__isnull', True), ('sender_page__isnull', False)), _connector='OR'), name='chk_message_sender'),
        ),
        migrations.AddConstraint(
            model_name='followpage',
            constraint=models.UniqueConstraint(fields=('user', 'page'), name='uniq_user_page_follow'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('page__isnull', True)), models.Q(('user__isnull', True), ('page__isnull', False)), _connector='OR'), name='chk_conversation_member_author'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('conversation', 'user'), name='uniq_conversation_user'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.UniqueConstraint(condition=models.Q(('page__isnull', False)), fields=('conversation', 'page'), name='uniq_conversation_page'),
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('page__isnull', True)), models.Q(('user__isnull', True), ('page__isnull', False)), _connector='OR'), name='chk_comment_reaction_author'),
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('comment', 'user'), name='uniq_comment_reaction_user'),
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('page__isnull', False)), fields=('comment', 'page'), name='uniq_comment_reaction_page'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('author_user__isnull', False), ('author_page__isnull', True)), models.Q(('author_user__isnull', True), ('author_page__isnull', False)), _connector='OR'), name='chk_post_author'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('author_user__isnull', False), ('author_page__isnull', True)), models.Q(('author_user__isnull', True), ('author_page__isnull', False)), _connector='OR'), name='chk_comment_author'),
        ),
        migrations.AddConstraint(
            model_name='postmedia',
            constraint=models.UniqueConstraint(fields=('post', 'order_index'), name='uniq_post_media_order'),
        ),
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('page__isnull', True)), models.Q(('user__isnull', True), ('page__isnull', False)), _connector='OR'), name='chk_post_reaction_author'),
        ),
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'user'), name='uniq_post_reaction_user'),
        ),
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('page__isnull', False)), fields=('post', 'page'), name='uniq_post_reaction_page'),
        ),
    ]
