# Generated by Django 5.2.5 on 2026-04-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_page',
            field=models.ForeignKey(blank=True, db_column='page_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.page'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('accepted_friend_request', 'Accepted Friend Request'), ('announcements', 'Announcements'), ('like', 'Like'), ('comment', 'Comment'), ('message', 'Message'), ('upcoming_event', 'Upcoming Event'), ('system', 'System'), ('reacted_post', 'Reacted to your post')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('is_read', False), ('receiver_user__isnull', False)), fields=['receiver_user'], name='notif_unread_user_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('is_read', False), ('receiver_page__isnull', False)), fields=['receiver_page'], name='notif_unread_page_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='notif_generic_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notif_created_at_idx'),
        ),
    ]
