# Generated by Django 5.2.11 on 2026-03-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('university', 'University'), ('educational', 'Educational'), ('library', 'Library'), ('lab', 'Lab'), ('cafeteria', 'Cafeteria'), ('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('shop', 'Shop'), ('gym', 'Gym'), ('student_club', 'Student Club'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
