# Generated by Django 5.2.11 on 2026-03-02 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_page_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityDomain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='email_domains', to='api.page')),
            ],
            options={
                'db_table': 'university_domain',
                'indexes': [models.Index(fields=['domain'], name='university__domain_2bc8da_idx')],
            },
        ),
    ]
