# Generated by Django 5.2.5 on 2026-05-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_notification_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('accepted_friend_request', 'Accepted Friend Request'), ('announcements', 'Announcements'), ('like', 'Like'), ('comment', 'Comment'), ('message', 'Message'), ('upcoming_event', 'Upcoming Event'), ('system', 'System'), ('reacted_post', 'Reacted to your post'), ('post_created', 'New Post Created')], max_length=30),
        ),
        migrations.DeleteModel(
            name='userphone',
        ),
    ]
