# Generated by Django 5.2.11 on 2026-03-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_universitydomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AlterField(
            model_name='messagemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('url', 'URL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('url', 'URL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
