# Generated by Django 5.2.11 on 2026-03-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_messagemedia_media_file_postmedia_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemedia',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
