# Generated by Django 5.2.5 on 2026-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_academic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructor',
            name='community_picks',
            field=models.ManyToManyField(blank=True, related_name='picked_by_instructors', to='api.community'),
        ),
    ]
