# Generated by Django 5.2.5 on 2026-05-06 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conversation_is_academic_instructor_community_picks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventreminder',
            name='uniq_event_user_time',
        ),
        migrations.AddConstraint(
            model_name='eventreminder',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='uniq_event_user_time'),
        ),
    ]
