# Generated by Django 5.2.11 on 2026-03-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_page_banner_image_page_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
