# Generated by Django 5.2.11 on 2026-03-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_communitymember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='community',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
