# Generated by Django 5.2.5 on 2026-05-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.post'),
        ),
    ]
