# Generated by Django 5.2.5 on 2026-04-12 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment_replying_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replying_to_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor_page',
            field=models.ForeignKey(blank=True, db_column='actor_page_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='api.page'),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor_user',
            field=models.ForeignKey(blank=True, db_column='actor_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.conversation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('accepted_friend_request', 'Accepted friend request'), ('announcements', 'Announcements'), ('like', 'Like'), ('comment', 'Comment'), ('friend_request', 'Friend Request'), ('message', 'Message'), ('event', 'Event'), ('system', 'System')], max_length=30),
        ),
    ]
