# Generated by Django 5.2.5 on 2026-05-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.post'),
        ),
    ]
