# Generated by Django 5.2.5 on 2026-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_comment_replying_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Accepted friend request', 'accepted_friend_request'), ('Announcements', 'announcements'), ('like', 'Like'), ('comment', 'Comment'), ('Friend Request', 'friend_request'), ('Message', 'message'), ('Upcoming Event', 'upcoming_event'), ('System', 'system'), ('React to your post', 'reacted_to_your_post')], max_length=30),
        ),
    ]
