# Generated by Django 5.2.5 on 2026-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_message_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='page_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='page_name_arabic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
