# Generated by Django 5.2.5 on 2026-04-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Accepted friend request', 'Accepted Friend Request'), ('Announcements', 'Announcements'), ('like', 'Like'), ('comment', 'Comment'), ('Friend Request', 'Friend Request'), ('Message', 'Message'), ('Upcoming Event', 'Upcoming Event'), ('System', 'System'), ('React to your post', 'Reacted To Your Post')], max_length=30),
        ),
    ]
