# Generated by Django 5.2.5 on 2026-04-12 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
        migrations.RemoveConstraint(
            model_name='conversationmember',
            name='chk_conversation_member_author',
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_by_page',
            field=models.ForeignKey(blank=True, db_column='created_by_page_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to='api.page'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_by_user',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='conversation_images', verbose_name='conversation image'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, db_column='last_message_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='conversation name'),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('created_by_user__isnull', False), ('created_by_page__isnull', True)), models.Q(('created_by_user__isnull', True), ('created_by_page__isnull', False)), models.Q(('created_by_user__isnull', True), ('created_by_page__isnull', True)), _connector='OR'), name='chk_conversation_creator'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('page__isnull', True)), models.Q(('user__isnull', True), ('page__isnull', False)), _connector='OR'), name='chk_conversation_member_actor'),
        ),
    ]
