# Generated by Django 5.2.5 on 2026-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_event_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_full_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
