# Generated by Django 5.2.5 on 2026-04-12 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
