# Generated by Django 5.2.5 on 2026-05-13 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_page_page_full_name_alter_page_page_name'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content_type_obj',
            field=models.ForeignKey(db_column='content_type_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='object_id',
            field=models.PositiveBigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('harassment_abuse', 'Harassment & Abuse'), ('violence_harm', 'Violence & Harm'), ('sexual_content_exploitation', 'Sexual Content & Exploitation'), ('child_safety', 'Child Safety'), ('hate_extremism', 'Hate & Extremism'), ('self_harm_dangerous_behavior', 'Self-Harm & Dangerous Behavior'), ('misinformation_manipulation', 'Misinformation & Manipulation'), ('privacy_impersonation', 'Privacy & Impersonation'), ('spam_scams_fraud', 'Spam, Scams & Fraud'), ('illegal_ip_violations', 'Illegal & Intellectual Property Violations'), ('other', 'Other')], max_length=50),
        ),
    ]
