# Generated by Django 5.2.5 on 2026-04-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_conversationmember_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, db_column='parent_message_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.message'),
        ),
    ]
