# Generated by Django 5.2.5 on 2026-04-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_message_parent_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='created_by_page',
        ),
    ]
