# Generated by Django 5.2.5 on 2026-05-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_report_content_type_obj_report_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_content_id',
        ),
    ]
