# Generated by Django 5.2.5 on 2026-04-12 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_conversation_created_by_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='chk_conversation_creator',
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_group', True), ('created_by_user__isnull', False)), models.Q(('is_group', False), ('created_by_user__isnull', True)), _connector='OR'), name='chk_conversation_creator'),
        ),
    ]
