# Generated by Django 5.2.5 on 2026-05-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_report_reported_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
