# Generated by Django 5.2.5 on 2026-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_pagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
