# Generated by Django 5.2.5 on 2026-04-13 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_conversationmember_chk_group_no_pages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDegree',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('degree_type', models.CharField(choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=20)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_degree',
            },
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_phone',
                'constraints': [models.UniqueConstraint(fields=('user', 'phone'), name='uniq_user_phone')],
            },
        ),
    ]
