# Generated by Django 5.2.5 on 2026-04-16 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userdegree_userphone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdegree',
            name='degree_type',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'Phd')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-sent_at'], name='message_convers_b5b7c0_idx'),
        ),
    ]
