# Generated by Django 5.2.5 on 2026-05-14 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_conversationmember_cleared_at'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='chk_comment_author',
        ),
        migrations.RemoveConstraint(
            model_name='commentreaction',
            name='chk_comment_reaction_author',
        ),
        migrations.RemoveConstraint(
            model_name='commentreaction',
            name='uniq_comment_reaction_page',
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='chk_conversation_creator',
        ),
        migrations.RemoveConstraint(
            model_name='conversationmember',
            name='chk_conversation_member_actor',
        ),
        migrations.RemoveConstraint(
            model_name='conversationmember',
            name='uniq_conversation_page',
        ),
        migrations.RemoveConstraint(
            model_name='message',
            name='chk_message_sender',
        ),
        migrations.RemoveConstraint(
            model_name='messagereaction',
            name='chk_message_reaction_author',
        ),
        migrations.RemoveConstraint(
            model_name='messagereaction',
            name='uniq_msg_reaction_page_type',
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='chk_post_author',
        ),
        migrations.RemoveConstraint(
            model_name='postreaction',
            name='chk_post_reaction_author',
        ),
        migrations.RemoveConstraint(
            model_name='postreaction',
            name='uniq_post_reaction_page',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_unread_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_unread_page_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='actor_user',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='receiver_user',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_page',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_user',
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='page',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='conversationmember',
            name='page',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_page',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_user',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='page',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='actor_page',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver_page',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_page',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_user',
        ),
        migrations.RemoveField(
            model_name='postreaction',
            name='page',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter_page',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, db_column='sender_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='page',
            name='user',
            field=models.OneToOneField(blank=True, null=True, db_column='user_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='page', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, db_column='reporter_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('is_read', False), ('receiver__isnull', False)), fields=['receiver'], name='notif_unread_idx'),
        ),
    ]
