# Generated by Django 5.2.5 on 2026-05-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_page_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_name',
        ),
    ]
