# Generated by Django 5.2.5 on 2026-05-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_notification_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='relation_type',
            field=models.CharField(choices=[('user_to_user', 'User To User'), ('user_to_page', 'User To Page')], default='user_to_user', max_length=20),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('following', 'Following')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='FollowPage',
        ),
    ]
