# Generated by Django 5.2.5 on 2026-05-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_friendship_relation_type_alter_friendship_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('url', 'URL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('url', 'URL')], max_length=10),
        ),
    ]
