# Generated by Django 5.2.5 on 2026-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_messagemedia_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
