# Generated by Django 5.2.5 on 2026-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userprofile_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='FriendsListPrivacy',
            field=models.CharField(choices=[('EVERYONE', 'Everyone'), ('FRIENDS_ONLY', 'Friends Only'), ('ONLY_ME', 'Only Me')], default='EVERYONE', max_length=15),
        ),
    ]
