# Generated by Django 5.2.5 on 2026-05-19 18:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_userprofile_friendslistprivacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_all', models.BooleanField(default=True)),
                ('friend_request', models.BooleanField(default=True)),
                ('post_reacted', models.BooleanField(default=True)),
                ('post_commented', models.BooleanField(default=True)),
                ('comment_replied', models.BooleanField(default=True)),
                ('community_new_post', models.BooleanField(default=True)),
                ('community_join_request_status', models.BooleanField(default=True)),
                ('event_starting_soon', models.BooleanField(default=True)),
                ('event_reminder_days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('event_updated_cancelled', models.BooleanField(default=True)),
                ('event_started', models.BooleanField(default=True)),
                ('page_announcement', models.BooleanField(default=True)),
                ('dm_existing_chat', models.BooleanField(default=True)),
                ('dm_new_request', models.BooleanField(default=True)),
                ('course_group_chat', models.BooleanField(default=True)),
                ('password_changed', models.BooleanField(default=True)),
                ('email_updated', models.BooleanField(default=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_setting',
            },
        ),
    ]
