# Generated by Django 5.2.5 on 2026-05-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_notificationsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='FriendsListPrivacy',
            new_name='friends_list_privacy',
        ),
    ]
