# Generated by Django 5.2.5 on 2026-05-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_friendslistprivacy_userprofile_friends_list_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsetting',
            old_name='course_group_chat',
            new_name='group_chat',
        ),
    ]
