# Generated by Django 5.2.5 on 2026-05-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_course_group_chat_notificationsetting_group_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Request'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
    ]
