# Generated by Django 5.2.5 on 2026-05-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_conversation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='event_reminder_days',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='event_started',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='event_starting_soon',
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='new_event',
            field=models.BooleanField(default=True),
        ),
    ]
