# Generated by Django 5.2.5 on 2026-05-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_notificationsetting_event_reminder_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
    ]
