# Generated by Django 5.2.5 on 2026-05-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_friendship_is_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
    ]
