# Generated by Django 5.2.5 on 2026-05-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_communitymember_is_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='allow_members_to_add_others',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='allow_members_to_edit_settings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='allow_members_to_send_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends_list_privacy',
            field=models.CharField(choices=[('EVERYONE', 'Everyone'), ('FRIENDS_ONLY', 'Friends Only'), ('NOBODY', 'Nobody')], default='EVERYONE', max_length=15),
        ),
    ]
