# Generated by Django 5.2.5 on 2026-05-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_conversation_allow_members_to_add_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='message_privacy',
            field=models.CharField(choices=[('EVERYONE', 'Everyone'), ('FRIENDS_ONLY', 'Friends Only'), ('NOBODY', 'Nobody')], default='EVERYONE', max_length=15),
        ),
    ]
