# Generated by Django 5.2.5 on 2026-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_conversation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='requires_post_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='highlighted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='final_action',
            field=models.CharField(choices=[('content_removal', 'Content removal'), ('warning_strike', 'Warning / Strike'), ('temp_restriction', 'Temporary restriction (limited features or short suspension)'), ('temp_suspension', 'Temporary suspension'), ('permanent_ban', 'Permanent ban'), ('account_deletion', 'Account deletion'), ('content_labeling', 'Content labeling (warning / sensitive tag)'), ('report_authorities', 'Report to authorities (for severe illegal cases)'), ('dismissed', 'Dismissed / False Alarm')], max_length=50),
        ),
    ]
