# Generated by Django 5.2.5 on 2026-06-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_community_requires_post_approval_post_highlighted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='relation_type',
            field=models.CharField(choices=[('user_to_user', 'User To User'), ('user_to_page', 'User To Page'), ('page_to_page', 'Page To Page')], default='user_to_user', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.BigAutoField(db_column='media_id', primary_key=True, serialize=False),
        ),
    ]
