# Generated by Django 5.2.5 on 2026-06-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_community_requires_post_approval_post_highlighted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
