# Generated by Django 5.2.5 on 2026-06-06 21:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_communityrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='can_instructors_post',
            field=models.BooleanField(db_column='can_instructors_post', default=True),
        ),
        migrations.AddField(
            model_name='community',
            name='can_pages_post',
            field=models.BooleanField(db_column='can_pages_post', default=True),
        ),
        migrations.AddField(
            model_name='community',
            name='can_students_post',
            field=models.BooleanField(db_column='can_students_post', default=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.BigAutoField(db_column='subscription_id', primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('basic', 'Basic Subscription'), ('premium', 'Premium Subscription'), ('university', 'University (Custom)')], default='basic', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='The price stored in USD', max_digits=6)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('custom', 'Custom Contract')], default='monthly', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Null means lifetime or indefinite until cancellation', null=True)),
                ('page', models.OneToOneField(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.page')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
    ]
