# Generated by Django 5.2.5 on 2026-06-07 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_community_can_instructors_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', default=6, on_delete=django.db.models.deletion.PROTECT, related_name='owned_communities', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
