# Generated by Django 5.2.5 on 2026-06-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_page_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPosition',
            fields=[
                ('position_id', models.BigAutoField(db_column='position_id', primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('primary', 'Primary'), ('part_time', 'Part Time')], default='primary', max_length=15)),
                ('instructor', models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_positions', to='api.instructor')),
            ],
            options={
                'db_table': 'teaching_position',
            },
        ),
    ]
