# Generated by Django 5.2.5 on 2026-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_teachingposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Request'), ('accepted', 'Accepted')], default='accepted', max_length=20),
        ),
    ]
