# Generated by Django 5.2.11 on 2026-06-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_conversation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=50),
        ),
    ]
