# Generated by Django 5.2.5 on 2026-06-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_conversationmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.BigAutoField(db_column='message_id', primary_key=True, serialize=False),
        ),
    ]
