# Generated by Django 5.2.5 on 2026-06-14 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_message_message_id'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.BigAutoField(db_column='promotion_id', primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ONHOLD', 'ONHOLD'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('content_type_obj', models.ForeignKey(db_column='content_type_id', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('promoted_by', models.ForeignKey(db_column='promoted_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promotion',
            },
        ),
    ]
