# Generated by Django 5.2.5 on 2026-06-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='requires_post_approval',
            field=models.BooleanField(default=False),
        ),
    ]
