# Generated by Django 5.2.5 on 2026-06-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_communitymember_requires_post_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymember',
            name='requires_post_approval',
        ),
    ]
