# Generated by Django 5.2.11 on 2026-06-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_communitymember_requires_post_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='promotion',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='duration_idx',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
