# Generated by Django 5.2.5 on 2026-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
