# Generated by Django 5.2.5 on 2026-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_userprofile_recovery_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends_list_privacy',
            field=models.CharField(choices=[('EVERYONE', 'Everyone'), ('FRIENDS_ONLY', 'Friends Only'), ('ONLY_ME', 'Only Me')], default='EVERYONE', max_length=15),
        ),
    ]
