# Generated by Django 5.2.5 on 2026-06-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_userprofile_friends_list_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='new_event',
        ),
    ]
