# Generated by Django 5.2.5 on 2026-06-16 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_remove_notificationsetting_new_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('news_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news_banners/')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
