# Generated by Django 5.2.5 on 2026-06-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='new_event',
            field=models.BooleanField(default=True),
        ),
    ]
