# Generated by Django 5.2.5 on 2026-06-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_notificationsetting_new_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
