# Generated by Django 5.2.5 on 2026-06-18 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_post_end_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAdReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('good', 'Good'), ('neutral', 'Neutral'), ('bad', 'Bad')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='ad_reactions', to='api.post')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='ad_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_ad_reaction',
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_user_ad_reaction')],
            },
        ),
    ]
