# Generated by Django 5.2.5 on 2026-06-18 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_postadreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('bug_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('action_track', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='support/bugs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactTicket',
            fields=[
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='support/tickets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contact_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
