# Generated by Django 5.2.5 on 2026-06-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_bugreport_contactticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('accepted_friend_request', 'Accepted Friend Request'), ('announcements', 'Announcements'), ('like', 'Like'), ('comment', 'Comment'), ('message', 'Message'), ('new_event', 'New Event'), ('event_update', 'Event Update'), ('system', 'System'), ('reacted_post', 'Reacted to your post'), ('commented_post', 'Commented on your post'), ('post_created', 'New Post Created'), ('dm-request', 'DM Request'), ('community_admin_alert', 'Community Admin Alert'), ('community_join_status', 'Community Join Status')], max_length=30),
        ),
    ]
