# Generated by Django 5.2.5 on 2026-06-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_comment_edited_at_comment_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('university', 'University'), ('collaborator', 'Collaborator'), ('educational', 'Educational'), ('library', 'Library'), ('lab', 'Lab'), ('cafeteria', 'Cafeteria'), ('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('shop', 'Shop'), ('gym', 'Gym'), ('student_club', 'Student Club'), ('service', 'Service'), ('local_business', 'Local Business'), ('Youth Developer Organization', 'Youth Developer Organization'), ('telecommunication', 'Telecommunication'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
