# Generated by Django 5.2.11 on 2026-06-19 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_page_page_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='api.post')),
            ],
            options={
                'db_table': 'poll_option',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.polloption')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poll_vote',
                'constraints': [models.UniqueConstraint(fields=('user', 'option'), name='uniq_user_poll_option')],
            },
        ),
    ]
