# Generated by Django 5.2.11 on 2026-06-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_add_poll_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
