# Generated by Django 5.2.11 on 2026-06-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_add_left_at_to_conversation_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline'), ('suspended', 'Suspended')], default='offline', max_length=12),
        ),
    ]
