# Generated by Django 5.2.5 on 2026-06-20 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_add_left_at_to_conversation_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='user',
            field=models.OneToOneField(db_column='user_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='page', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
