# Generated by Django 5.2.11 on 2026-06-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_userprofile_default_status_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
