# Generated by Django 5.2.11 on 2026-06-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_page_user'),
        ('api', '0069_message_is_forwarded'),
    ]

    operations = [
    ]
