# Generated by Django 5.2.5 on 2026-06-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_merge_0068_alter_page_user_0069_message_is_forwarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
