from django.contrib import admin

from .models import (
    Admin,
    Comment,
    CommentReaction,
    Community,
    CommunityMember,
    Conversation,
    ConversationMember,
    EmailVerification,
    Event,
    EventReminder,
    FollowPage,
    Friendship,
    Instructor,
    Message,
    MessageMedia,
    MessageReaction,
    Notification,
    Page,
    Post,
    PostMedia,
    PostReaction,
    Report,
    Student,
    UserProfile,
)

admin.site.register(UserProfile)
admin.site.register(EmailVerification)
admin.site.register(Page)
admin.site.register(Admin)
admin.site.register(Instructor)
admin.site.register(Student)
admin.site.register(Friendship)
admin.site.register(Notification)
admin.site.register(Community)
admin.site.register(CommunityMember)
admin.site.register(Event)
admin.site.register(EventReminder)
admin.site.register(Post)
admin.site.register(PostMedia)
admin.site.register(Comment)
admin.site.register(PostReaction)
admin.site.register(CommentReaction)
admin.site.register(FollowPage)
admin.site.register(Conversation)
admin.site.register(ConversationMember)
admin.site.register(Message)
admin.site.register(MessageMedia)
admin.site.register(MessageReaction)
admin.site.register(Report)
